<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTV1OZ5c\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTV1OZ5c/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTV1OZ5c.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTV1OZ5c\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTV1OZ5c\App_KernelDevDebugContainer([
    'container.build_hash' => 'TV1OZ5c',
    'container.build_id' => '8c051334',
    'container.build_time' => 1756991490,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTV1OZ5c');
